runtime: nodejs20
service: incomming-inventory-form-main
instance_class: F2
handlers:
  - url: /assets
    static_dir: dist/assets

  - url: /vite.svg
    static_files: dist/vite.svg
    upload: dist/vite.svg

  - url: /
    static_files: dist/index.html
    upload: dist/index.html
